# This page is a temporary page, allowing us to input a summary and receive a JSON output
# This JSON output will be eventually parsed into a webpage template
# For now, visualization and validation of the output is the goal
import streamlit as st
import ollama
from pydantic import BaseModel

# JSON model for the JSON that will be generated by the webpage generator LLM
# Pydantic gives the LLM a clear structure to follow when generating the JSON, which should lead to consistent results
# View this link for more information: https://docs.ollama.com/capabilities/structured-outputs
class WebpageContents(BaseModel):
    header: str
    subheader: str
    content: str

class WebpageJSON(BaseModel):
    elements: list[WebpageContents]
 
# Generate the JSON response from the model   
def privacy_policy_json(summary, client):
    privacy_policy_webpage_generator = "webpage-json"  # Model name
    
    response = client.generate(
        model=privacy_policy_webpage_generator,
        prompt=summary,
        format=WebpageJSON.model_json_schema() # tells the model how to format the JSON
    )
    return response["response"]

# Introductory text
st.markdown("""
            <h1 style='text-align: center;'>
                AI Privacy Policy Helper JSON Visualizer
            </h1>
            
            <h2 style='text-align: center;'>
                Gives quick access to the JSON generated by the LLM
            </h2>
          """, unsafe_allow_html=True)

# Text input box, copied from Welcome.py
privacy_policy_text = st.text_area(
    "Paste the privacy policy summary below:",
    height=300
)

# Button to generate the JSON, mostly copied from Welcome.py
if st.button("Generate JSON"):
    if not privacy_policy_text.strip():
        st.warning("Please enter some text first.")
    
    with st.spinner("Generating JSON..."):
        client = ollama.Client()
        summary = privacy_policy_json(privacy_policy_text, client)
        
    st.subheader("Generated JSON")
    st.json(summary)
