# Nutrition Label Template page
# Uses streamlit_extras to create a Nutrition Label-esc template for the user's summarized privacy policy
# Rough draft at the moment, and will need a great deal of refining

import streamlit as st
from streamlit_extras.grid import grid

# Assigns a grid layout to the page
# First column has only 1 cell, second column has two cells, and the third column has 1 cell
grid_example = grid(1, 2, 1, vertical_align="top")

# Expander function creates a collapsible section in the streamlit app, which is useful for organizing content 
# It also formats the content in a nice format that follows quite closely to the nutriton label format
with grid_example.expander("🔒 Data privacy", expanded=True):
    # Use HTML in st.markdown to display the content
    # It's considered "unsafe" due to cross-site scripting attacks
    # ^^^ We're not using any user input in this HTML, so we won't have to worry about this
    # This applies to all columns that are created
    st.markdown("""
                <h1 style='text-align: center;'>
                    <u>Nutrition Label Template</u>
                </h1>
                
                <p style='text-align: center; font-size: 15px;'>
                    This is an example of what the nutrition label template could look like! <br /><br />
                    This is just a placeholder for now, but we will eventually have this template generated by our AI models based on the privacy policy text input by the user. <br /><br />
                    The goal is to have a consistent format for all privacy policies, making it easier for users to understand.
                </p>
                
                """, unsafe_allow_html=True)
with grid_example.expander("🔍 Data collection", expanded=True):
    st.markdown("""
            <h1 style='text-align: center;'>
                <u>Data Collection</u>
            </h1>
            
            <p style='text-align: center; font-size: 15px;'>
                This data is being collected from you: <br />
            </p>
            <div style='display: flex; gap: 10px; text-align: center;'>
                <div style='flex: 1;'>🔍 Data point 1</div>
                <div style='flex: 1;'>🔍 Data point 2</div>
            </div>
            """, unsafe_allow_html=True)

        
with grid_example.expander("🔧 Actions You Can Take", expanded=True):
    st.markdown("""
            <h1 style='text-align: center;'>
                <u>Actions You Can Take</u>
            </h1>
            
            <p style='text-align: center; font-size: 15px;'>
                Placeholder text.
            </p>
            """, unsafe_allow_html=True)

with grid_example.expander("Gaps in This Privacy Policy", expanded=True):
    st.markdown("""
            <h1 style='text-align: center;'>
                <u>Gaps in This Privacy Policy</u>
            </h1>
            
            <p style='text-align: center; font-size: 15px;'>
                Placeholder text.
            </p>
            """, unsafe_allow_html=True)