# LLM functions module
# This module handles all of the LLM calls and JSON schema validation for the application
# This was originally in Welcome.py, but was moved to its own module to keep the code clean

import json
from pydantic import BaseModel

# Pydantic models for the JSON generated by the webpage LLM
# This form of JSON validation is recommended by Ollama's documentation
# Saves time when it comes to cleaning the JSON output
# DOCUMENTATION: https://docs.ollama.com/capabilities/structured-outputs#example-extract-structured-data

# SummaryJSON is the format of the summary generated by the first LLM
# Splits the privacy policy summary into 6 different sections, which are some of the most common sections found in privacy policies
# Check policy-summarizer to see the prompt engineering for this model
class SummaryJSON(BaseModel):
    data_usage: str
    data_collection: str
    third_party_sharing: str
    user_rights: str
    security: str
    gaps_and_recommendations: str

# WebpageJSON is the format of the JSON generated by the second LLM, which is used to create the webpage templates
# Takes into account the JSON schema from SummaryJSON and creates headers, subheaders and bullet points based on the content of each section
# Check webpage-generator to see the prompt engineering for this model
class WebpageContents(BaseModel):
    header: str
    subheader: str
    content: str

class WebpageJSON(BaseModel):
    elements: list[WebpageContents]

# Segmentation of duties
# Having one LLM responsible for summarization and JSON formatting led to weird generation issues
# This implementation splits the focus across two models instead
def privacy_policy_summary(privacy_policy_text, client):
    model_name = "privacy-policy-summarizer"

    # Give the model the raw privacy policy text, and have it generate a summary in the format specified by the SummaryJSON pydantic model
    response = client.generate(
        model=model_name,
        prompt=privacy_policy_text,
        format=SummaryJSON.model_json_schema()
    )

    # Return the response as a string
    return response["response"]

# Second model that generates JSON based on the summary
# Smaller models benefit greatly from having a more focused task
def webpage_generator(privacy_policy_summary, client):
    model_name = "webpage-generator"

    # Give this model the JSON object generated by the first model, and have it generate a new JSON in the format specified by the WebpageJSON pydantic model
    response = client.generate(
        model=model_name,
        prompt=privacy_policy_summary,
        format=WebpageJSON.model_json_schema()
    )

    # Response from the model is a string, use json.loads to convert it into a JSON object that can be parsed
    return json.loads(response["response"])