# LLM functions module
# This module handles all of the LLM calls and JSON schema validation for the application
# This was originally in Welcome.py, but was moved to its own module to keep the code clean
import json
from pydantic_ai import Agent
from pydantic_ai.models.ollama import OllamaModel
from pydantic_ai.providers.ollama import OllamaProvider
from pydantic import BaseModel
from pages.system_prompts import policy_summarizer_system_prompt, webpage_generator_system_prompt

# SummaryJSON is the format of the summary generated by the first LLM
# Splits the privacy policy summary into 6 different sections, which are some of the most common sections found in privacy policies
# Check policy-summarizer to see the prompt engineering for this model
class SummaryJSON(BaseModel):
    data_usage: str
    data_collection: str
    third_party_sharing: str
    user_rights: str
    security: str
    gaps_and_recommendations: str

# WebpageJSON is the format of the JSON generated by the second LLM, which is used to create the webpage templates
# Takes into account the JSON schema from SummaryJSON and creates headers, subheaders and bullet points based on the content of each section
# Check webpage-generator to see the prompt engineering for this model
class WebpageContents(BaseModel):
    header: str
    subheader: str
    content: str

class WebpageJSON(BaseModel):
    elements: list[WebpageContents]

# Instantiate the Ollama client
# API implementation using Pydantic AI's Ollama integration: https://pydantic.dev/docs/ai/models/ollama/
# Uses Pydantic AI so that JSON output is validated by the Pydantic models above
model = OllamaModel(
    "nemotron-3-super:cloud",
    provider=OllamaProvider(base_url="https://ollama.com/v1", api_key="your api key here")
)

# Creates an agent for the summarizer model, provides it with a system prompt and the SummaryJSON pydantic model to validate the output
agent_summarizer = Agent(model, system_prompt=policy_summarizer_system_prompt(), output_type=SummaryJSON, retries=2)
agent_webpage_generator = Agent(model, system_prompt=webpage_generator_system_prompt(), output_type=WebpageJSON, retries=2)

# Segmentation of duties
# Having one LLM responsible for summarization and JSON formatting led to weird generation issues
# This implementation splits the focus across two models instead
def privacy_policy_summary(privacy_policy_text):

    # Give the model the raw privacy policy text and have it generate a summary in the format specified by the SummaryJSON pydantic model
    # Return the response as a string
    response = agent_summarizer.run_sync(privacy_policy_text)
    return response.output.model_dump()

# Second model that generates JSON based on the summary
# Smaller models benefit greatly from having a more focused task
def webpage_generator(privacy_policy_summary):

    # Give this model the JSON object generated by the first model, and have it generate a new JSON in the format specified by the WebpageJSON pydantic model
    # Response from the model is a string, use json.loads to convert it into a JSON object that can be parsed
    response = agent_webpage_generator.run_sync(privacy_policy_summary)
    return response.output.model_dump()